preview: "@previewincor_new"
context:
  metadata: "bum"
  title: "Work with us"
  subtitle: "Procedure"
  description: "In order to be recruited as an official by an EU institution, you need to pass an open competition organised at the inter-institutional level by the European Personnel Selection Office. The Committee of the Regions also employs temporary or contract staff."
  cta:
  poster:
    src: "https://images.unsplash.com/photo-1508873699372-7aeab60b44ab?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80"
    alt: "alternative text"
  projects:
    - image:
        src: "/assets/images/jobs/nextstop.png"
        alt: "alt text"
      link:
        text: " YFactor presents: Next Stop podcast  "
        target: "www.greenpeace.org"
    - image:
        src: "/assets/images/jobs/yfactorconf.png"
        alt: "alt text"
      link:
        text: "YFactor Conference 2015"
        target: "www.greenpeace.org"
    - image:
        src: "/assets/images/jobs/yfactorevent.png"
        alt: "alt text"
      link:
        text: "YFactor Event 2018 - Citizen's Dialogue in Molenbeek"
        target: "www.greenpeace.org"
