preview: "@previewincor_new"
context:
  metadata: "bum"
  title: "Work with us"
  subtitle: "Traineeships"
  description: "The CoR is a relatively young institution and, as such, recognizes the importance of giving voice to the ideas of newcomers and younger generations. Involving young people in the EU decision-making process is precisely the aim of the CoR traineeship programme."
  cta:
    - target: "https://trainee.cor.europa.eu/Form.aspx?m=i&culture=en"
      text: "Apply now"
    - target: "https://cor.europa.eu/en/about/Pages/traineeships.aspx"
      text: "Learn more about our traineeships opportunities"
  poster:
    src: "https://cor.europa.eu/en/about/PublishingImages/Traineeship/pictures_of_trainees.jpg"
    alt: "alternative text"
  projects:
    - image:
        src: "/assets/images/jobs/nextstop.png"
        alt: "alt text"
      link:
        text: " YFactor presents: Next Stop podcast  "
        target: "www.greenpeace.org"
    - image:
        src: "/assets/images/jobs/yfactorconf.png"
        alt: "alt text"
      link:
        text: "YFactor Conference 2015"
        target: "www.greenpeace.org"
    - image:
        src: "/assets/images/jobs/yfactorevent.png"
        alt: "alt text"
      link:
        text: "YFactor Event 2018 - Citizen's Dialogue in Molenbeek"
        target: "www.greenpeace.org"
  testimonials:
    - quote: "This traineeship is a unique opportunity to work in an international environment and discover the institutions from the inside!"
      author: "Kimberly Orinx"
      more: "Protocol Service, Belgium"
      img: "/assets/images/jobs/traineeships/Kimberlysquare.png"
    - quote: "Don't be afraid of joining what might appear to be a bureaucratic institution - in reality the countless office doors hide friendly colleagues who appreciate your contribution and personal interests."
      author: "Florian Klee"
      more: "Cabinet of the Secretary General, Germany"
      img: "/assets/images/jobs/traineeships/Floriansquare.png"
    - quote: "Working for the Renew Europe group in the CoR is like being a part of a big family, as your team not only tries to make your traineeship as valuable as possible, but your performance is wanted and very much valued."
      author: "Myriam Zöllner"
      more: "Renew Europe group in the CoR, Germany"
      img: "/assets/images/jobs/traineeships/Myriamsquare.png"
    - quote: "Being involved in the work of a smaller institution like the CoR gives you the opportunity to see how the EU works in practice"
      author: "Szilvia Fejes"
      more: "Unit A1 Services to members and eCoR, Hungary"
      img: "/assets/images/jobs/traineeships/Szilviasquare.png"
    - quote: "The traineeship has been a good opportunity to consilidate my professional skills and expand my knowledge in the field of European affairs."
      author: "Valeria Núñez Morpurgo"
      more: "Unit C3 SEDEC Commision, Spain/Italy"
      img: "/assets/images/jobs/traineeships/Valeriasquare.png"
    - quote: "At the start, if you do your traineeship in one of the political groups, you will be overwhelmed with the wide variety of topics discussed and tasks given to you."
      author: "Simonas Obcarskas"
      more: "EA political group, Lithuania"
      img: "/assets/images/jobs/traineeships/Simonassquare.png"
    - quote: "Expect a lot of variety and flexibility from your traineeship at the CoR. You will be warmly welcomed to your team, then get given lots of tasks. But don't fret: You'll find help should you require it."
      author: "Vanessa Pogacnik Murillo"
      more: "Unit B3 Civex Commission, Germany/Slovenia/Mexico"
      img: "/assets/images/jobs/traineeships/Vanessasquare.png"
    - quote: "I was given the opportunity to grow with the tasks assigned to me and expand my skills in multiple areas, My opinion was valued from the first dayand I was able to contribute actively to my unit's progress."
      author: "Wiebke Krieger"
      more: "Unit D3 Communication, Germany"
      img: "/assets/images/jobs/traineeships/Wiebkesquare.png"
