preview: "@previewincor_new"
context:
  metadata: "bum"
  title: "Work with us"
  subtitle: "Assistant (Temporary Staff Member AST3) at the Renew Europe political group"
  description: "
    *Reference*: COR/AST3/33/20/RE
    Directorate:
    Function Group: AST
    Management: No
    Deadline:18/01/2021 12:00
    Job Title: Assistant (Office Manager) - Temporary Staff Member
    Unit/Service: Renew Europe Group
    Grade: AST3 (Temporary Staff Member)
    Location: Brussels
    ​NATURE OF THE DUTIES AND PROFILE"
  cta:
  poster:
    src: "/assets/images/jobs/corbuilding.jpeg"
    alt: "alternative text"
