preview: "@previewincor_new"
context:
  title: "Work with us"
  subtitle: ""
  cta:
    - text: Join us
      link: "https://seashepherd.org"
  poster:
    src: "/assets/images/future-of-europe.png"
    alt: "alternative text"
  latestopportunities:
    - date: "01/06/2021"
      grade: "AST1 - AST7"
      jobtitle: "Project manager"
      link:
        text: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
        target: "document.pdf"
        size: "3 MB PDF"
    - date: "01/06/2021"
      grade: AST1 - AST7
      jobtitle: "Project manager"
      link:
        text: "Europe Day: discover the European Union on the occasion of 9 May 2021"
        target: "www.greenpeace.org"
    - date: "01/06/2021"
      grade: AST1 - AST7
      jobtitle: "Project manager"
      link:
        text: "European Citizens Initiatives (ECIs) conclusions should be subject of a serious follow up by European institutions"
        target: "2030 Regional Commitments"
