context:
  document:
    title: Preventing corruption at local and regional level in South Mediterranean countries
    src: google.be
    date: "12/11/2021"
    language: English
    size: 3 MB
    type: PDF
    cover: /assets/images/documentCover.png
    translations:
      - language: français
        title: FR Eu dolor magna elit reprehenderit sunt laborum consequat do ipsum sunt eu ad cillum eiusmod.
        size: 3.2 MB
        src: test.be
        type: PDF
      - language: English
        title: EN Eu dolor magna elit reprehenderit sunt laborum consequat do ipsum sunt eu ad cillum eiusmod.
        src: test.be
        size: 3.2 MB
        type: PDF
      - language: español
        title: ES Eu dolor magna elit reprehenderit sunt laborum consequat do ipsum sunt eu ad cillum eiusmod.
        src: test.be
        size: 3.2 MB
        type: PDF
    variations:
      - title: Titre du document
        language: français
        size: 3 MB
        type: PDF
      - title: Document title
        language: Deutsch
        size: 3 MB
        type: PDF
