context:
  document:
    title: Preventing corruption at local and regional level in South Mediterranean countries
    src: google.be
    language: English
    size: 3 MB
    type: PDF
    variations:
      - title: Titre du document
        language: français
        size: 3 MB
        type: PDF
      - title: Document title
        language: Deutsch
        size: 3 MB
        type: PDF
