variants:
  - name: sticky
    context:
      modifier: sticky
context:
  title: Contenu
  nav:
    - text: premier lien
      link:
    - text: deuxième lien
      link:
    - text: troisième lien
      link:
