context:
  tenders:
    - reference: CDR/2021/C1/1/COTER /BUDG
      title: Eiusmod quis ex officia ex aliquip. Eiusmod quis ex officia ex aliquip. Eiusmod quis ex officia ex aliquip. Duis Lorem consequat Lorem culpa voluptate occaecat labore sint elit eiusmod quis occaecat laborum eu. Incididunt sunt excepteur eiusmod quis exercitation velit consectetur excepteur adipisicing amet ea. Lorem laboris eiusmod veniam est duis. Ipsum culpa pariatur sit occaecat aute commodo nulla. Non in veniam reprehenderit adipisicing veniam cillum proident labore aliqua cillum deserunt velit. Enim commodo amet commodo nisi incididunt cupidatat.
      date: "20/12/2022"
      description: Aliqua dolor exercitation dolore qui irure aute pariatur cupidatat. Consectetur enim commodo nostrud dolore consequat veniam. Nulla et ut et mollit consequat commodo ad.
    - reference: CDR/2021/C1/1/COTER /BUDG
      title: Eiusmod quis ex officia ex aliquip.
      date: "20/12/2022"
      description: Aliqua dolor exercitation dolore qui irure aute pariatur cupidatat. Consectetur enim commodo nostrud dolore consequat veniam. Nulla et ut et mollit consequat commodo ad.
    - reference: CDR/2021/C1/1/COTER /BUDG
      title: Eiusmod quis ex officia ex aliquip.
      date: "20/12/2022"
      description: Aliqua dolor exercitation dolore qui irure aute pariatur cupidatat. Consectetur enim commodo nostrud dolore consequat veniam. Nulla et ut et mollit consequat commodo ad.
