context:
  image:
    src: "https://api.assetroulette.com/random_unsplash"
    alt: "Alternative text"
  date: "01/06/2021"
  title: "Local and regional leaders connect with European Parliament, European Commission and Bertelsmann Foundation to take forward actions on the Conference on the Future of Europe"
  link:
    text: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
    target: "document.pdf"
    size: "3 MB PDF"
  rapporteur:
    name: "Jane Doe"
variants:
  - name: "With background"
    context:
      modifier: "withbackground"
  - name: "Opinion"
    context:
      modifier: "opinion"
