context:
  videoContainerTitle: "Videos and others"
  video:
    fallbackText: "Votre navigateur ne permet pas de lire les vidéos HTML5."
    title: "Speech of the President of the European Committee of the Regions, Apostolos Tzitzikostas"
    sources:
      - type: "video/webm"
        file: "https://archive.org/download/WebmVp8Vorbis/webmvp8.webm"
      - type: "video/mp4"
        file: "https://archive.org/download/WebmVp8Vorbis/webmvp8_512kb.mp4"
      - type: "video/ogg"
        file: "https://archive.org/download/WebmVp8Vorbis/webmvp8.ogv"
    poster: "https://images.unsplash.com/photo-1485126813038-6bcabfed7bc6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=550&q=80"
  relatedVideos:
    - title: 'The green revolution: "the EU must not fail" - Juan Espadas'
      poster: "https://images.unsplash.com/photo-1485126813038-6bcabfed7bc6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=550&q=80"
      id: "15421"
    - title: 'The green revolution: "the EU must not fail" - Juan Espadas'
      poster: "https://images.unsplash.com/photo-1485126813038-6bcabfed7bc6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=550&q=80"
      id: "15421"
    - title: 'The green revolution: "the EU must not fail" - Juan Espadas'
      poster: "https://images.unsplash.com/photo-1485126813038-6bcabfed7bc6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=550&q=80"
      id: "15421"
    - title: 'The green revolution: "the EU must not fail" - Juan Espadas'
      poster: "https://images.unsplash.com/photo-1485126813038-6bcabfed7bc6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=550&q=80"
      id: "15421"
    - title: 'The green revolution: "the EU must not fail" - Juan Espadas'
      poster: "https://images.unsplash.com/photo-1485126813038-6bcabfed7bc6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=550&q=80"
      id: "15421"
