preview: "@previewincor"
context:
  title: Massive thanks to our partners
  partners:
    - alttext: "European Committee of the Regions"
      link: "cor.europa.eu"
      image: "/Style%20Library/Cor/style/img/Logos/logo_CoR-vertical-positive-fr-quadri_LR.png"
    - alttext: "Yolda"
      link: ""
      image: "/en/events/PublishingImages/ENVE8th/yolda.png"
    - alttext: "Euromontana"
      link: ""
      image: "/en/events/PublishingImages/ENVE8th/euromontana.png"
    - alttext: "International year of rangelands and pastoralists"
      link: ""
      image: "/en/events/PublishingImages/ENVE8th/iyrp.png"
