context:
  slides:
    - test
    - test
    - test
    - test
    - test
  testimonials:
    - quote: J'ai trouvé au Comité des Régions une vraie bienveillance entre collègues et de la part des supérieurs hiérarchiques. Le Comité des Régions a des valeurs fortes en matière d'égalité au travail. Que l'on soit AST, contractuel, interim ou AD, il n'y a pas de différence de traitement
      author: Agnès PHILIPPART
    - quote: Le CdR a une structure à taille humaine, qui permet un contact entre collègues plus personnalisé et un rôle dans la structure plus polyvalent. Ici, on ne collabore pas avec des "unités" ou des "directions" mais avec des collègues.
      author: Klaus HULLMANN
    - quote: Ce qui m'a attiré au Comité était le contact avec les élus locaux, travailler dans une institution politique qui fonctionne de façon similaire au Parlement européen mais a un réel ancrage sur le terrain, cherche à transformer le monde à partir d'expériences concrètes et vécues
      author: Delphine LANGLOIS
    - quote: La combinaison du caractère international et multiculturel du CdR avec son rôle d'institution proche des citoyens et de leur réalité de vie, en fait un lieu unique où travailler et œuvrer à la consolidation du projet européen.
      author: Paola CARUSO
    - quote: The CoR offers a multilingual and international working environment while at the same time it is a human-sized institution. It is a small world in a big one
      author: Heinrich BULTMANN
    - quote: Je suis très attaché au Sud-Ouest de la France et le fait de travailler pour le CDR à plus de 1100 kms de chez moi et ainsi y croiser régulièrement des intervenants ou visiteurs originaires de ma région, me donne la possibilité de communiquer, d'échanger, d'expliquer et ainsi donne un sens complémentaire à ma présence au sein du Comité.
      author: Christophe BOULANT
    - quote: At the coR, you stop being a number and become an appreciated human being and valuable staff member, and, up to my view, the possibilities for self-development are higher
      author: Yanira MORAN ROMERO
