preview: "@previewincor_new"
context:
  news:
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: 
        target: "www.cor.europa.eu"
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: 
        target: "www.cor.europa.eu"
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: 
        target: "www.cor.europa.eu"
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: 
        target: "www.cor.europa.eu"
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: 
        target: "www.cor.europa.eu"
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: 
        target: "www.cor.europa.eu"
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: 
        target: "www.cor.europa.eu"
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: 
        target: "www.cor.europa.eu"
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: 
        target: "www.cor.europa.eu"
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: 
        target: "www.cor.europa.eu"
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: 
        target: "www.cor.europa.eu"
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: 
        target: "www.cor.europa.eu"
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: 
        target: "www.cor.europa.eu"
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: 
        target: "www.cor.europa.eu"
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: 
        target: "www.cor.europa.eu"
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: 
        target: "www.cor.europa.eu"
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: 
        target: "www.cor.europa.eu"
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: 
        target: "www.cor.europa.eu"
