title: "Work with us"
preview: "@previewincor_new"
variants:
  - name: "Staging"
    preview: "@previewincor_new"
    context:
      css: "bouhou.css"
      staging: true
  - name: "Prod"
    preview: "@previewincor_prod"
    context:
      prod: true
context:
  metadata: "bum"
  title: "Future of Europe"
  subtitle: "Bringing Europe closer to its people"
  poster:
    src: "/assets/images/future-of-europe.png"
    alt: "alternative text"
  secondarynav:
    - name: "CIVEX"
      link: "https://cor.europa.eu/fr/our-work/Pages/civex.aspx"
    - name: "COTER"
      link: "https://cor.europa.eu/fr/our-work/Pages/coter.aspx"
    - name: "ECON"
      link: "https://cor.europa.eu/fr/our-work/Pages/econ.aspx"
    - name: "ENVE"
      link: "https://cor.europa.eu/fr/our-work/Pages/enve.aspx"
    - name: "NAT"
      link: "https://cor.europa.eu/fr/our-work/Pages/nat.aspx"
    - name: "CEDEC"
      link: "https://cor.europa.eu/fr/our-work/Pages/cedec.aspx"
  initiatives:
    - image:
        src: "https://images.unsplash.com/photo-1485126813038-6bcabfed7bc6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=550&q=80"
        alt: "alt text"
        copyright: "© European Union, 2020 "
      date: "01/06/2021"
      link:
        text: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
        target: "document.pdf"
        size: "3 MB PDF"
    - image:
        src: "https://images.unsplash.com/photo-1485126813038-6bcabfed7bc6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=550&q=80"
        alt: "alt text"
      date: "01/06/2021"
      link:
        text: "Europe Day: discover the European Union on the occasion of 9 May 2021"
        target: "www.greenpeace.org"
    - image:
        src: "https://images.unsplash.com/photo-1485126813038-6bcabfed7bc6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=550&q=80"
        alt: "alt text"
      date: "01/06/2021"
      link:
        text: "European Citizens Initiatives (ECIs) conclusions should be subject of a serious follow up by European institutions"
        target: "2030 Regional Commitments"
  news:
    - image:
        src: "https://images.unsplash.com/photo-1485126813038-6bcabfed7bc6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=550&q=80"
        alt: "alernative text"
      date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: "www.cor.europa.eu"
    - image:
        src: "https://images.unsplash.com/photo-1485126813038-6bcabfed7bc6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=550&q=80"
        alt: "alernative text"
      date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: "www.cor.europa.eu"
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: "www.cor.europa.eu"
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: "www.cor.europa.eu"
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: "www.cor.europa.eu"
  documents:
    - link:
        text: "The Bratislava healthier"
        target: "document.pdf"
        size: "3 MB PDF"
    - link:
        text: "Petržalka Youth Parliament"
        target: "document.pdf"
        size: "3 MB PDF"
    - link:
        text: "Green Deal"
        target: "document.pdf"
        size: "3 MB PDF"
  upcomingEvents:
    - image:
        src: "https://images.unsplash.com/photo-1485126813038-6bcabfed7bc6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=550&q=80"
        alt: "alernative text"
      date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: "www.cor.europa.eu"
    - image:
        src: "https://images.unsplash.com/photo-1485126813038-6bcabfed7bc6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=550&q=80"
        alt: "alernative text"
      date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: "www.cor.europa.eu"
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: "www.cor.europa.eu"
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: "www.cor.europa.eu"
  pastEvents:
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: "www.cor.europa.eu"
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: "www.cor.europa.eu"
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: "www.cor.europa.eu"
  adoptedOpinions:
    - image:
        src: "https://fakeface.rest/face/view/5?minimum_age=25"
        alt: "alernative text"
      title: "(CDR 722/2021) - Revised Trans-European Energy Infrastructure Regulation fit for the Green and Digital Transition"
      rapporteur: "Jane Doe"
      link: "www.cor.europa.eu"
    - image:
        src: "https://fakeface.rest/face/view/5?minimum_age=25"
        alt: "alernative text"
      date: "01/06/2021"
      title: "(CDR 1903/2021) - Forging a climate-resilient Europe - the new EU Strategy on Adaptation to Climate Change"
      rapporteur: "Jane Doe"
      link: "www.cor.europa.eu"
    - image:
        src: "https://fakeface.rest/face/view/5?minimum_age=25"
        alt: "alernative text"
      title: "(CDR 1903/2021) - Forging a climate-resilient Europe - the new EU Strategy on Adaptation to Climate Change"
      rapporteur: "Jane Doe"
      link: "www.cor.europa.eu"
    - image:
        src: "https://fakeface.rest/face/view/5?minimum_age=25"
        alt: "alernative text"
      title: "(CDR 1903/2021) - Forging a climate-resilient Europe - the new EU Strategy on Adaptation to Climate Change"
      rapporteur: "Jane Doe"
      link: "www.cor.europa.eu"
    - image:
        src: "https://fakeface.rest/face/view/5?minimum_age=25"
        alt: "alernative text"
      title: "(CDR 1903/2021) - Forging a climate-resilient Europe - the new EU Strategy on Adaptation to Climate Change"
      rapporteur: "Jane Doe"
      link: "www.cor.europa.eu"
    - image:
        src: "https://fakeface.rest/face/view/5?minimum_age=25"
        alt: "alernative text"
      title: "(CDR 1903/2021) - Forging a climate-resilient Europe - the new EU Strategy on Adaptation to Climate Change"
      rapporteur: "Jane Doe"
      link: "www.cor.europa.eu"
  indiscussionOpinions:
    - title: "(CDR 3170/2016) - Towards a sustainable EU food policy"
      link: "www.cor.europa.eu"
    - title: "(CDR 435/2018) - Local and regional incentives to promote healthy and sustainable diets"
      link: "www.cor.europa.eu"
    - title: "(CDR 3637/2018) - Reform of the CAP"
      link: "www.cor.europa.eu"
    - title: "(CDR 4601/2019) - Stepping up EU Action to Protect and Restore the World’s Forests"
      link: "www.cor.europa.eu"
    - title: "(CDR 4764/2019) - Implementation of Free Trade Agreements (FTAs): The regional and local perspective"
      link: "www.cor.europa.eu"
    - title: "(CDR 4829/2019) - AC The renewal of the Leipzig Charter on Sustainable European Cities"
      link: "www.cor.europa.eu"
    - title: "(CDR 539/2020) - Bio-diverse cities and regions beyond 2020 at the UN CBD COP 15 and in the EU Biodiversity Strategy for 2030"
      link: "www.cor.europa.eu"
    - title: "(CDR 549/2020) - Towards a Roadmap for Clean Hydrogen – the contribution of local and regional authorities to a climate-neutral Europe"
      link: "www.cor.europa.eu"
    - title: "(CDR 540/2020) - The Future of EU Clean Air policy in the framework of the zero-pollution ambition"
      link: "www.cor.europa.eu"
    - title: "(CDR 541/2020) - Fitness check of the Water Framework Directive, Groundwater Directive, Environmental Quality Standards Directive and Floods Directive"
      link: "www.cor.europa.eu"
    - title: "(CDR 594/2020) - From Farm to Fork the local and regional dimension"
      link: "www.cor.europa.eu"
    - title: "(CDR 418/2020) - Just Transition Fund"
      link: "www.cor.europa.eu"
