preview: "@previewincor"
context:
  title: "My website"
  initiatives:
    - title: "My website"
      image: "https://api.assetroulette.com/random_image"
      date: 01/06/2021
      textlink: "2030 Regional Commitments"
      document:
        size: "3 MB PDF"
    - title: "My website"
      image: "https://api.assetroulette.com/random_image"
      date: 01/06/2021
      textlink: "2030 Regional Commitments"
      document:
        size: "3 MB PDF"
    - title: "My website"
      image: "https://api.assetroulette.com/random_image"
      date: 01/06/2021
      textlink: "2030 Regional Commitments"
      document:
        size: "3 MB PDF"
