preview: "@previewincor_new"
context:
  title: "Future of Europe"
  subtitle: "Bringing Europe closer to its people"
  initiatives:
    - image: "https://api.assetroulette.com/random_unsplash"
      date: "01/06/2021"
      link:
        text: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
        target: "document.pdf"
        size: "3 MB PDF"
    - image: "https://api.assetroulette.com/random_unsplash"
      date: "01/06/2021"
      link:
        text: "Europe Day: discover the European Union on the occasion of 9 May 2021"
        target: "www.greenpeace.org"
    - image: "https://api.assetroulette.com/random_unsplash"
      date: "01/06/2021"
      link:
        text: "European Citizens Initiatives (ECIs) conclusions should be subject of a serious follow up by European institutions"
        target: "2030 Regional Commitments"
  news:
    - image:
        src: "https://api.assetroulette.com/random_unsplash"
        alt: "alernative text"
      date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: "www.cor.europa.eu"
    - image:
        src: "https://api.assetroulette.com/random_unsplash"
        alt: "alernative text"
      date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: "www.cor.europa.eu"
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: "www.cor.europa.eu"
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: "www.cor.europa.eu"
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: "www.cor.europa.eu"
  documents:
    - link:
        text: "The Bratislava healthier"
        target: "document.pdf"
        size: "3 MB PDF"
    - link:
        text: "Petržalka Youth Parliament"
        target: "document.pdf"
        size: "3 MB PDF"
    - link:
        text: "Green Deal"
        target: "document.pdf"
        size: "3 MB PDF"
  upcomingEvents:
    - image:
        src: "https://api.assetroulette.com/random_unsplash"
        alt: "alernative text"
      date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: "www.cor.europa.eu"
    - image:
        src: "https://api.assetroulette.com/random_unsplash"
        alt: "alernative text"
      date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: "www.cor.europa.eu"
  pastEvents:
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: "www.cor.europa.eu"
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: "www.cor.europa.eu"
    - date: "01/06/2021"
      title: "The Bratislava - Petržalka Youth Parliament debates how the European Green Deal can make the city of Bratislava greener and healthier"
      link: "www.cor.europa.eu"
