title: "Presidents"
preview: "@previewincor_new"
context:
  metadata: "bum"
  title: "Presidents"
  subtitle: "Bringing Europe closer to its people"
  description: "Exercitation amet ex aute veniam ut ea excepteur. Occaecat aliqua laborum eiusmod pariatur. Velit adipisicing aute aliqua consequat aliquip. Dolore consectetur consequat quis cupidatat cillum labore consectetur mollit."
  poster: false
  presidents:
    - name: "JaneDoe de JaneDoeJaneDoe"
      years: "2020 - 2016"
      description: "Voluptate sit excepteur non quis duis labore est anim. Do dolore fugiat tempor quis ea consequat. Cillum qui proident sint qui irure incididunt sit aliqua minim occaecat officia velit ex. Ad dolor tempor proident exercitation et nulla. Pariatur incididunt commodo proident enim cillum dolore incididunt."
      portrait:
        src: "https://picsum.photos/500/500"
        alt: "portrait of"
    - name: "Jane Doe"
      years: "2020 - 2016"
      description: "Voluptate sit excepteur non quis duis labore est anim. Do dolore fugiat tempor quis ea consequat. Cillum qui proident sint qui irure incididunt sit aliqua minim occaecat officia velit ex. Ad dolor tempor proident exercitation et nulla. Pariatur incididunt commodo proident enim cillum dolore incididunt."
      portrait:
        src: "https://picsum.photos/500/500"
        alt: "portrait of"
    - name: "Jane Doe"
      years: "2020 - 2016"
      description: "Voluptate sit excepteur non quis duis labore est anim. Do dolore fugiat tempor quis ea consequat. Cillum qui proident sint qui irure incididunt sit aliqua minim occaecat officia velit ex. Ad dolor tempor proident exercitation et nulla. Pariatur incididunt commodo proident enim cillum dolore incididunt."
      portrait:
        src: "https://picsum.photos/500/500"
        alt: "portrait of"
    - name: "Jane Doe"
      years: "2020 - 2016"
      description: "Voluptate sit excepteur non quis duis labore est anim. Do dolore fugiat tempor quis ea consequat. Cillum qui proident sint qui irure incididunt sit aliqua minim occaecat officia velit ex. Ad dolor tempor proident exercitation et nulla. Pariatur incididunt commodo proident enim cillum dolore incididunt."
      portrait:
        src: "https://picsum.photos/500/500"
        alt: "portrait of"
    - name: "Jane Doe"
      years: "2020 - 2016"
      description: "Voluptate sit excepteur non quis duis labore est anim. Do dolore fugiat tempor quis ea consequat. Cillum qui proident sint qui irure incididunt sit aliqua minim occaecat officia velit ex. Ad dolor tempor proident exercitation et nulla. Pariatur incididunt commodo proident enim cillum dolore incididunt."
      portrait:
        src: "https://picsum.photos/500/500"
        alt: "portrait of"
    - name: "Jane Doe"
      years: "2020 - 2016"
      description: "Voluptate sit excepteur non quis duis labore est anim. Do dolore fugiat tempor quis ea consequat. Cillum qui proident sint qui irure incididunt sit aliqua minim occaecat officia velit ex. Ad dolor tempor proident exercitation et nulla. Pariatur incididunt commodo proident enim cillum dolore incididunt."
      portrait:
        src: "https://picsum.photos/500/500"
        alt: "portrait of"
