preview: "@previewincor"
context:
  title: Massive thanks to our partners
  partners:
    - alttext: "partner name 1"
      link: "http://www.greenpeace.org"
      image: "http://placekitten.com/200/200"
    - alttext: "partner name 2"
      link: "http://www.greenpeace.org"
      image: "http://placekitten.com/200/200"
    - alttext: "partner name 3"
      link: "http://www.greenpeace.org"
      image: "http://placekitten.com/200/200"
    - alttext: "partner name 4"
      link: "http://www.greenpeace.org"
      image: "http://placekitten.com/200/200"
    - alttext: "partner name 5"
      link: "http://www.greenpeace.org"
      image: "http://placekitten.com/200/200"
